//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkingAds.MessageBroker.Resx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class QueueNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal QueueNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ParkingAds.MessageBroker.Resx.QueueNames", typeof(QueueNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ParkingAdsDebugLog.
        /// </summary>
        internal static string DebugLog {
            get {
                return ResourceManager.GetString("DebugLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ParkingAdsLog.
        /// </summary>
        internal static string DefaultLog {
            get {
                return ResourceManager.GetString("DefaultLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ParkingAdsErrorLog.
        /// </summary>
        internal static string ErrorLog {
            get {
                return ResourceManager.GetString("ErrorLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ParkingAdsInfoLog.
        /// </summary>
        internal static string InfoLog {
            get {
                return ResourceManager.GetString("InfoLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ParkingAdsTraceLog.
        /// </summary>
        internal static string TraceLog {
            get {
                return ResourceManager.GetString("TraceLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ParkingAdsWarnLog.
        /// </summary>
        internal static string WarnLog {
            get {
                return ResourceManager.GetString("WarnLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ParkingAdsWiretap.
        /// </summary>
        internal static string Wiretap {
            get {
                return ResourceManager.GetString("Wiretap", resourceCulture);
            }
        }
    }
}
